name: spa_router
version: 0.1.0+1
author: Kornel Maczyński <kornel661@gmail.com>
description: >
  Routing element for HTML5 single page applications (declarative syntax :-))
  written in Polymer.dart.
homepage: https://github.com/kornel661/spa-router
environment:
  sdk: '>=1.8.5'
dependencies:
  browser: '^0.10.0+2'
  core_elements: '^0.6.1+2'
  polymer: '^0.16.0+6'
  template_binding: '^0.14.0+2'
dev_dependencies:
  unittest: '^0.11.5+4'
transformers:
- polymer:
    entry_points:
    - example/index.html
    - example/transitions.html
