name: web_router
version: 0.0.1
author: Kornel Maczyński <kornel661@gmail.com>
description: Routing element for HTML5 single page applications (declarative syntax :-)) written in Polymer.dart.
homepage: https://github.com/kornel661/web-router
environment:
  sdk: '>=1.8.5 <2.0.0'
dependencies:
  browser: '^0.10.0+2'
  core_elements: '^0.6.1+1'
  polymer: '^0.16.0+3'
  template_binding: '^0.14.0+1'
dev_dependencies:
  unittest: '^0.11.5+4'
  paper_elements: '^0.6.2+1'
transformers:
- polymer:
    entry_points: example/index.html